### PR TITLE
DHT11 import issue, packaging and readme fixes

### PR DESCRIPTION
**Pull request by praveen-garg**
- [x] Fix README and add info for creating and installing as a debian package 
- [x] Added info why pip3 dep does not work and we need to build package manually, to use plugin
- [x] Fix config handle
- [x] FOGL-1533 workaround
- [x] Testing

- [ ] revisit docs/06_plugins/03_01_DHT11.rst and docs/06_plugins/02_writing_plugins.rst
- [ ] Add https://s3.amazonaws.com/foglamp/docs/v1/Common/plugins/South/DHT11/DHT11-RaspPI-pins.jpg  with DHT11 sensor mapping

### CODE REVIEW

**Comment by praveen-garg** [comment]
Known issue: https://github.com/adafruit/Adafruit_Python_DHT/issues/99

**Comment by praveen-garg** [comment]
dht-11-sensor-data

dht-11-pin-connection-2
dht-11-pin-connection

**Review by AmandeepArora — APPROVED** [review]
It is working fine now.

**Comment by praveen-garg** [comment]
@MarkRiddoch  Please review.

**Review by MarkRiddoch — APPROVED** [review]

**Pull request merged**
